redis:
  image: redis

db:
  image: postgres:9.4
    environment:
     POSTGRES_PASSWORD: 1234
vote:
  image: dockersamples/examplevotingapp_vote
  ports:
    - 5000:80
  links:
    - redis:redis 

result:
  image: dockersamples/examplevotingapp_result
  ports:
    - 5001:80
  links:
    - db

worker:
  image: dockersamples/examplevotingapp_worker
  links:
    - db
    - redis
